config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # get 'categories', to: 'categories#index'
  resources :categories, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :category
  belongs_to :recipe

  validates :comment, length: { minimum: 6, too_short: 'must have at least 6 characters' }
  validates :recipe_id, uniqueness: { scope: :category_id, message: 'is already bookmarked in this category' }
end

app/models/category.rb
# Category class
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks
  has_many :categories, through: :bookmarks

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new
  end

  def create
    @category = Category.find(params[:category_id])
    @bookmark = @category.bookmarks.create(bookmark_params)
    if @bookmark.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to category_path(@bookmark.category)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :recipe_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new # Needed to instantiate the form_with
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@category, @bookmark] do |f| %>
  <%= f.association :recipe %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>
<%= link_to "Back", category_path(@category)%>

app/views/categories/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
  <div class="container">
    <h1>Cookbook</h1>
     <p>Save your favourites recipes</p>
  </div>
</div>
<div class="mid_sec_container">
  <h3>List of categories</h3>
  <%= link_to "New category", new_category_path, class: "btn btn-flat" %>
</div>

<div class="cards">
  <% @categories.each do |category| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
      <%= link_to category.name, category_path(category)%>
    </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<!-- app/views/restaurants/new.html.erb -->
<%= simple_form_for @category do |f| %>
    <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

<%= link_to "Back", categories_path %>

app/views/categories/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
  <div class="container">
    <h1><%= @category.name %></h1>
  </div>
</div>
<div class="mid_sec_container">
  <h3>Recipes</h3>
  <%= link_to "Add recipe", new_category_bookmark_path(@category), class: "btn btn-flat" %>
</div>

<div class="cards">
  <% @category.bookmarks.each do |bookmark| %>
    <div class="card-trip">
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
      <div class="card-trip-infos">
        <%= bookmark.recipe.name %>
        <%= bookmark.recipe.rating %>
        <%= bookmark.comment %>
        <%= link_to "|Delete",
          bookmark_path(bookmark),
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
        %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "Back", categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New category", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
              <%# link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>